import type { RegistryEntry } from "../../shared.ts";

export const adapta_webProvider: RegistryEntry = {
  id: "adapta-web",
  alias: "adp-web",
  format: "openai",
  executor: "adapta-web",
  baseUrl: "https://agent.adapta.one/api/chat/stream/v1",
  authType: "apikey",
  authHeader: "bearer",
  models: [
    { id: "adapta-one", name: "ONE (via Adapta)", toolCalling: false },
    { id: "adapta-one-pro", name: "ONE Pro (via Adapta)", toolCalling: false },
    { id: "adapta-one-superfast", name: "ONE Superfast (via Adapta)", toolCalling: false },
    { id: "adapta-gpt-56-luna", name: "GPT-5.6 Luna (via Adapta)", toolCalling: false },
    { id: "adapta-gpt-54-mini", name: "GPT-5.4 Fast (via Adapta)", toolCalling: false },
    { id: "adapta-claude-5-sonnet", name: "Claude 5 Sonnet (via Adapta)", toolCalling: false },
    { id: "adapta-claude-4-6-sonnet", name: "Claude 4.6 Sonnet (via Adapta)", toolCalling: false },
    { id: "adapta-claude-4-5-haiku", name: "Claude 4.5 Haiku (via Adapta)", toolCalling: false },
    { id: "adapta-gemini-3-5-flash", name: "Gemini 3.5 Flash (via Adapta)", toolCalling: false },
    {
      id: "adapta-gemini-3-1-pro-preview",
      name: "Gemini 3.1 Pro (via Adapta)",
      toolCalling: false,
    },
    { id: "adapta-kimi-k2-7-code", name: "Kimi K2.7 Code (via Adapta)", toolCalling: false },
    { id: "adapta-kimi-k2-6", name: "Kimi K2.6 (via Adapta)", toolCalling: false },
    { id: "adapta-kimi-k2-5", name: "Kimi K2.5 (via Adapta)", toolCalling: false },
    { id: "adapta-minimax-m3", name: "MiniMax M3 (via Adapta)", toolCalling: false },
    {
      id: "adapta-minimax-m2-7-highspeed",
      name: "MiniMax M2.7 Highspeed (via Adapta)",
      toolCalling: false,
    },
    { id: "adapta-minimax-m2-7", name: "MiniMax M2.7 (via Adapta)", toolCalling: false },
    { id: "adapta-qwen-3-7-plus", name: "Qwen 3.7 Plus (via Adapta)", toolCalling: false },
    { id: "adapta-qwen-3-6-plus", name: "Qwen 3.6 Plus (via Adapta)", toolCalling: false },
    { id: "adapta-qwen-3-5-flash", name: "Qwen 3.5 Flash (via Adapta)", toolCalling: false },
    { id: "adapta-glm-5-2", name: "GLM 5.2 (via Adapta)", toolCalling: false },
    { id: "adapta-deepseek", name: "DeepSeek V4 (via Adapta)", toolCalling: false },
    { id: "adapta-grok-43", name: "Grok 4.3 (via Adapta)", toolCalling: false },
    { id: "adapta-muse-spark-1-1", name: "Muse Spark 1.1 (via Adapta)", toolCalling: false },
    { id: "adapta-sonar-pro", name: "Perplexity (via Adapta)", toolCalling: false },
    { id: "adapta-nvidia-nemotron-super", name: "Nemotron Super (via Adapta)", toolCalling: false },
  ],
};
